### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by Rhilip** [pdfcopy/pdfcopy.github.io#1]
无法访问 https://pdfcopy.cn/

看 README.md 的更新，似乎是不再使用该域名，但是如果直接访问 更新后的 pdfcopy.github.io 网址，又会因为仓库中的 CNAME文件导致被重定向回 pdfcopy.cn

![image](https://user-images.githubusercontent.com/13842140/103645443-f4741580-4f92-11eb-8107-9e6217cf0446.png)

**Comment by OddCN** [comment]
@Rhilip  谢谢提醒！ 刚刚续费了域名，现在应该可以了。请问最近在使用 pdfcopy 么？

**Comment by Rhilip** [comment]
昨天想用的时候发现这个问题，之前有使用过一段时间。
既然fix了就关掉了。
